using System.Collections.ObjectModel;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;
using CommunityToolkit.Mvvm.ComponentModel;
using MolaGPT.Core.Chat;
using MolaGPT.Core.Models;
using MolaGPT.Storage;
using MolaGPT.Storage.Repositories;
using MolaGPT.ViewModels.Services;

namespace MolaGPT.ViewModels;

/// <summary>
/// View model for the active chat. Holds the message list, the active
/// (provider, model) pair, streaming state, hint chips for the welcome screen
/// and, when available, the SQLite-backed message repository.
/// </summary>
public sealed partial class ChatViewModel : ObservableObject
{
    // Bulk-capable so opening a conversation publishes one collection change
    // instead of one per message: every Add is a separate notification, and the
    // transcript turns each into its own row insert, so a 10-message
    // conversation used to raise ~300 CollectionChanged events on the UI thread
    // before the first frame. Streaming still appends one message at a time.
    private readonly BulkObservableCollection<MessageViewModel> _messages = new();
    public ObservableCollection<MessageViewModel> Messages => _messages;

    /// <summary>
    /// Session-level artifacts: files currently in this conversation's Python
    /// working directory (generated by the python tool or uploaded by the user).
    /// Surfaced in the artifact side panel. Refreshed on conversation load and
    /// after each python tool run via <see cref="RefreshArtifacts"/>.
    /// </summary>
    public ObservableCollection<ArtifactItemViewModel> Artifacts { get; } = new();

    /// <summary>True when the current conversation has at least one artifact;
    /// drives the header toggle's badge / enabled state.</summary>
    public bool HasArtifacts => Artifacts.Count > 0;

    /// <summary>Artifact count for the header badge.</summary>
    public int ArtifactCount => Artifacts.Count;

    /// <summary>Raised after <see cref="RefreshArtifacts"/> recomputes the list.
    /// Carries whether the current conversation now has any artifacts so the
    /// shell can auto-open/close the artifact panel per conversation.</summary>
    public event EventHandler<bool>? ArtifactsRefreshed;

    /// <summary>
    /// Re-scans the conversation's Python working directory and repopulates
    /// <see cref="Artifacts"/>. Cheap directory enumeration; safe to call on the
    /// UI thread after a tool run or when switching conversations. No-op shape
    /// (empty list) when nothing has been generated/uploaded yet.
    /// </summary>
    public void RefreshArtifacts()
    {
        var scanned = string.IsNullOrEmpty(ConversationId)
            ? Array.Empty<MolaGPT.Core.Chat.Tools.PythonExecution.WorkspaceArtifact>()
            : MolaGPT.Core.Chat.Tools.PythonExecution.WorkspaceArtifactScanner.Scan(ConversationId);

        Artifacts.Clear();
        foreach (var artifact in scanned)
            Artifacts.Add(new ArtifactItemViewModel(artifact));

        OnPropertyChanged(nameof(HasArtifacts));
        OnPropertyChanged(nameof(ArtifactCount));
        ArtifactsRefreshed?.Invoke(this, HasArtifacts);
    }


    /// <summary>Default prompt suggestions shown on the welcome screen.</summary>
    public ObservableCollection<string> HintChips { get; } = new()
    {
        "用 Markdown 输出快速排序",
        "把这段话翻译成英文",
        "今天有什么新闻?",
        "推荐三本科幻小说"
    };

    [ObservableProperty] private string? _conversationId;
    [ObservableProperty] private string _conversationTitle = "新对话";
    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(IsBYOKActive))]
    [NotifyPropertyChangedFor(nameof(CurrentMode))]
    [NotifyPropertyChangedFor(nameof(ActiveModeLabel))]
    private IChatProvider? _activeProvider;
    [ObservableProperty] private ProviderModel? _activeModel;
    [ObservableProperty] private bool _isStreaming;
    [ObservableProperty] private string? _conversationSystemPrompt;

    /// <summary>
    /// Persona bound to the current conversation, or null if none.
    /// Persisted in <c>conversations.persona_id</c>.
    /// </summary>
    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(ActivePersona))]
    [NotifyPropertyChangedFor(nameof(ActivePersonaAvatar))]
    [NotifyPropertyChangedFor(nameof(ActivePersonaName))]
    [NotifyPropertyChangedFor(nameof(ActivePersonaSystemPrompt))]
    private string? _activePersonaId;

    /// <summary>
    /// How <see cref="ConversationSystemPrompt"/> combines with the active
    /// persona's prompt: <c>"override"</c> (default) replaces the persona
    /// prompt; <c>"append"</c> concatenates persona + "\n\n" + override.
    /// Persisted in <c>conversations.system_prompt_mode</c>.
    /// </summary>
    [ObservableProperty] private string _systemPromptMode = "override";

    /// <summary>
    /// System prompt configured at the model level (from ProviderModelEntry.SystemPrompt).
    /// Set externally by MainViewModel when the active model changes.
    /// Retained for backward compatibility; used only when no persona is bound.
    /// </summary>
    public string? ActiveModelSystemPrompt { get; set; }

    /// <summary>The persona view-model bound to the current conversation, or null.</summary>
    public PersonaItemViewModel? ActivePersona => _personas?.Find(ActivePersonaId);

    /// <summary>Avatar glyph shown by Composer / Welcome / dialog whether or
    /// not a persona is bound. Returns the default robot glyph when no
    /// persona is active so XAML doesn't need FallbackValue gymnastics.</summary>
    public string ActivePersonaAvatar => ActivePersona is { } p
        ? p.DisplayAvatar
        : PersonaIconCatalog.DefaultGlyph;

    /// <summary>Display name for the active persona, or "角色" when none.</summary>
    public string ActivePersonaName => ActivePersona?.Name ?? "角色";

    /// <summary>Shortcut for the active persona's prompt text. Null when no persona is bound
    /// or the persona has an empty prompt.</summary>
    public string? ActivePersonaSystemPrompt
    {
        get
        {
            var p = ActivePersona;
            return string.IsNullOrWhiteSpace(p?.SystemPrompt) ? null : p!.SystemPrompt;
        }
    }

    /// <summary>Persona registry, exposed so XAML (WelcomeView quick-pick row,
    /// Composer picker) can bind to <c>Personas.Personas</c> without going
    /// through MainViewModel.</summary>
    public PersonaListViewModel? Personas => _personas;

    /// <summary>True when persona-related surfaces should be shown. We treat
    /// "no provider yet" as BYOK because the welcome screen needs to surface
    /// roles before the user has signed in to MolaGPT. Semantically this is
    /// "local-agent mode" (BYOK or Work) — both run the agent loop locally with
    /// the local-tools toolbar; only Chat (MolaGPT proxy) hides it.</summary>
    public bool IsBYOKActive =>
        _personas is not null && CurrentMode.IsLocalAgent();

    /// <summary>Explicit three-way app mode (Byok / Chat / Work) derived from the
    /// active provider. UI-layer truth source for the sidebar mode slider, quota
    /// chip visibility, and per-mode labels. See <see cref="AppMode"/>.</summary>
    public AppMode CurrentMode => ActiveProvider.ToAppMode();

    /// <summary>Per-mode provider subtitle shown beside the model name in the
    /// top-bar pill: "BYOK · 自带密钥" / "MolaGPT 账号" / "MolaGPT 共享额度".</summary>
    public string ActiveModeLabel => CurrentMode switch
    {
        AppMode.Chat => "MolaGPT 账号",
        AppMode.Work => "   ",
        _ => ActiveProvider is null ? "BYOK · 自带密钥" : $"{ActiveProvider.DisplayName} · BYOK",
    };

    /// <summary>True iff <see cref="Messages"/> is empty; drives welcome screen visibility.</summary>
    public bool IsEmpty => Messages.Count == 0;

    /// <summary>
    /// True while a conversation is being loaded into <see cref="Messages"/>.
    /// Drives a loading indicator so a multi-second load of a large
    /// conversation doesn't look like a frozen app. Cleared as soon as the
    /// first batch of messages is materialized (first paint), even though
    /// MarkdownPresenter may still be appending blocks for huge messages in the
    /// background.
    /// </summary>
    [ObservableProperty] private bool _isConversationLoading;
    [ObservableProperty] private bool _autoCollapseThinking = true;

    public string ActiveModelLabel => ActiveModel?.DisplayName ?? "未选择";
    public string ActiveProviderLabel => ActiveProvider?.DisplayName ?? "未选择";

    /// <summary>
    /// Context pressure for the open conversation. Lives here rather than on the
    /// composer because it belongs to the transcript: switching conversations has to
    /// switch the reading with it, or the gauge shows one conversation's fullness
    /// over another's messages.
    /// </summary>
    public ContextGaugeViewModel ContextGauge { get; } = new();

    private readonly ProviderRegistry _providers;
    private readonly MessageRepository? _messageRepo;
    private readonly ConversationRepository? _conversationRepo;
    private readonly PersonaListViewModel? _personas;
    private readonly SettingsRepository? _settingsRepo;
    private int _messageLoadVersion;

    /// <summary>
    /// Optional sink for timing traces, wired by the desktop layer to PerfLog.
    /// Kept as a delegate so the view-model project stays UI-free.
    /// </summary>
    public static Action<string, string?>? PerfTrace { get; set; }

    /// <summary>How many of the newest messages a conversation opens with —
    /// enough to overfill a maximized viewport so the user lands on the latest
    /// reply rather than a half-empty screen.</summary>
    private const int TailBatch = 15;

    /// <summary>
    /// The rest of the conversation: read from SQLite but deliberately not
    /// materialized into <see cref="Messages"/>. Kept in chronological order;
    /// the view pulls from the tail of this list as the user scrolls up
    /// (see <see cref="LoadOlderMessages"/>).
    /// </summary>
    private readonly List<PreparedMessage> _pendingOlderMessages = [];

    /// <summary>True while part of this conversation's history is still parked
    /// in <see cref="_pendingOlderMessages"/>. Drives the view's scroll-up
    /// paging.</summary>
    public bool HasOlderMessages => _pendingOlderMessages.Count > 0;

    /// <summary>
    /// Raised whenever a conversation row was created or its title / updated_at
    /// moved. <see cref="ConversationListViewModel"/> subscribes so the sidebar
    /// reflects the change without a full SQLite reload.
    /// </summary>
    public event EventHandler<ConversationTouchedEventArgs>? ConversationTouched;

    public ChatViewModel(ProviderRegistry providers)
        : this(providers, null, null, null) { }

    public ChatViewModel(
        ProviderRegistry providers,
        MessageRepository? messageRepo,
        ConversationRepository? conversationRepo)
        : this(providers, messageRepo, conversationRepo, null) { }

    public ChatViewModel(
        ProviderRegistry providers,
        MessageRepository? messageRepo,
        ConversationRepository? conversationRepo,
        PersonaListViewModel? personas)
        : this(providers, messageRepo, conversationRepo, personas, null) { }

    public ChatViewModel(
        ProviderRegistry providers,
        MessageRepository? messageRepo,
        ConversationRepository? conversationRepo,
        PersonaListViewModel? personas,
        SettingsRepository? settingsRepo)
    {
        _providers = providers;
        _messageRepo = messageRepo;
        _conversationRepo = conversationRepo;
        _personas = personas;
        _settingsRepo = settingsRepo;

        Messages.CollectionChanged += (_, _) =>
        {
            OnPropertyChanged(nameof(IsEmpty));
            UpdateLatestAssistantFlags();
        };
        _providers.Changed += (_, _) => RefreshActiveModelAfterProviderChange();

        // When the user edits the active persona's prompt, the resolved
        // ActivePersonaSystemPrompt changes value-wise even if the id didn't.
        if (_personas is not null)
            _personas.PersonasChanged += (_, _) =>
            {
                OnPropertyChanged(nameof(ActivePersona));
                OnPropertyChanged(nameof(ActivePersonaAvatar));
                OnPropertyChanged(nameof(ActivePersonaName));
                OnPropertyChanged(nameof(ActivePersonaSystemPrompt));
            };

        ActivePersonaId = ResolveDefaultPersonaId();
        TryAutoPickActive();
    }

    /// <summary>If no provider is currently active, pick the first registered one.</summary>
    public void TryAutoPickActive()
    {
        if (ActiveProvider is not null && ActiveModel is not null) return;
        var first = _providers.Providers.FirstOrDefault();
        if (first is null || first.Models.Count == 0) return;
        ActiveProvider = first;
        ActiveModel = first.Models[0];
    }

    public void SetActive(IChatProvider provider, ProviderModel model)
    {
        ActiveProvider = provider;
        ActiveModel = model;
    }

    public bool SetActiveByIds(string? providerId, string? modelId, bool ignoreConversationBoundary = false)
    {
        if (string.IsNullOrWhiteSpace(providerId) || string.IsNullOrWhiteSpace(modelId))
            return false;

        var resolved = _providers.FindModel(providerId, modelId);
        if (resolved is null) return false;
        if (!ignoreConversationBoundary && !CanSwitchToProvider(resolved.Value.Provider))
            return false;

        SetActive(resolved.Value.Provider, resolved.Value.Model);
        RememberModeSelection(resolved.Value.Provider.ToAppMode(), providerId, modelId);
        return true;
    }

    public bool CanSwitchToProvider(IChatProvider provider)
    {
        // Boundary is by capability, not wallet: a Chat (cloud) conversation can
        // only continue with the proxy; a local-agent conversation (Work or BYOK)
        // can continue with either local-tools or any BYOK provider.
        var family = GetCurrentConversationProviderFamily();
        return family switch
        {
            ConversationProviderFamily.Chat => provider.Kind == ProviderKind.MolaGptProxy,
            ConversationProviderFamily.Agent => provider.Kind != ProviderKind.MolaGptProxy,
            _ => true
        };
    }

    // ===== Three-way mode slider (BYOK / Chat / Work) =====
    // The slider is the UI truth source for AppMode. Switching modes routes to
    // each mode's representative provider: Chat → molagpt-proxy, Work →
    // molagpt-local-tools, BYOK → the user's last-chosen BYOK provider (or the
    // first registered one). The active provider drives CurrentMode back, so the
    // slider thumb always reflects reality. Per-mode (provider,model) memory
    // persists via SettingsRepository.

    private const string ModeLastProviderKeyPrefix = "mode_last_provider_";
    private const string ModeLastModelKeyPrefix = "mode_last_model_";

    /// <summary>Switch to the representative provider of the given mode. Returns
    /// false (and surfaces a login request via <paramref name="needsLogin"/>) when
    /// the target MolaGPT-account provider isn't registered (user not signed in).</summary>
    public bool SwitchToMode(AppMode mode, out bool needsLogin)
    {
        needsLogin = false;
        var (providerId, modelId) = ResolveModeTarget(mode, out needsLogin);
        if (providerId is null || modelId is null) return false;

        if (SetActiveByIds(providerId, modelId, ignoreConversationBoundary: true))
        {
            RememberModeSelection(mode, providerId, modelId);
            return true;
        }
        return false;
    }

    private (string? ProviderId, string? ModelId) ResolveModeTarget(AppMode mode, out bool needsLogin)
    {
        needsLogin = false;
        switch (mode)
        {
            case AppMode.Chat:
            {
                var p = _providers.GetById(MolaGptProviderIds.Proxy);
                if (p is null) { needsLogin = true; return (null, null); }
                return (p.Id, RecallModel(p) ?? p.Models.FirstOrDefault()?.Id);
            }
            case AppMode.Work:
            {
                // "MolaGPT Work" is the unified local-agent capability. Land on the
                // agent provider the user last used (shared-quota Work or a BYOK
                // provider); fall back to shared-quota Work, then the first BYOK.
                var lastAgentId = _settingsRepo?.Get(ModeLastProviderKeyPrefix + "agent");
                var provider = string.IsNullOrWhiteSpace(lastAgentId) ? null : _providers.GetById(lastAgentId!);
                if (provider is null || provider.Kind == ProviderKind.MolaGptProxy)
                    provider = _providers.GetById(MolaGptProviderIds.LocalTools)
                               ?? _providers.Providers.FirstOrDefault(p => !p.Kind.IsMolaGptAccount());
                if (provider is null) { needsLogin = true; return (null, null); }
                return (provider.Id, RecallModel(provider) ?? provider.Models.FirstOrDefault()?.Id);
            }
            default:
            {
                // BYOK: last-chosen BYOK provider if still registered, else first BYOK.
                var byok = _providers.Providers.Where(p => !p.Kind.IsMolaGptAccount()).ToList();
                if (byok.Count == 0) return (null, null);
                var lastId = _settingsRepo?.Get(ModeLastProviderKeyPrefix + "byok");
                var chosen = byok.FirstOrDefault(p => p.Id == lastId) ?? byok[0];
                return (chosen.Id, RecallModel(chosen) ?? chosen.Models.FirstOrDefault()?.Id);
            }
        }
    }

    private string? RecallModel(IChatProvider provider)
    {
        var key = ModeLastModelKeyPrefix + provider.Id;
        var recalled = _settingsRepo?.Get(key);
        return string.IsNullOrWhiteSpace(recalled) ? null : recalled;
    }

    private void RememberModeSelection(AppMode mode, string providerId, string modelId)
    {
        if (_settingsRepo is null) return;
        _settingsRepo.Set(ModeLastProviderKeyPrefix + mode.ToString().ToLowerInvariant(), providerId);
        _settingsRepo.Set(ModeLastModelKeyPrefix + providerId, modelId);
        // The unified "MolaGPT Work" switcher button lands on whichever agent
        // provider was last active — shared-quota Work or a BYOK provider.
        if (mode.IsLocalAgent())
            _settingsRepo.Set(ModeLastProviderKeyPrefix + "agent", providerId);
    }

    public void SaveConversationSystemPrompt(string? prompt)
    {
        ConversationSystemPrompt = string.IsNullOrWhiteSpace(prompt) ? null : prompt.Trim();
        if (_conversationRepo is null || string.IsNullOrEmpty(ConversationId)) return;
        var existing = _conversationRepo.Get(ConversationId!);
        if (existing is null) return;
        _conversationRepo.Upsert(existing with { SystemPrompt = ConversationSystemPrompt });
    }

    /// <summary>
    /// Bind the current conversation to a persona (or unbind by passing null).
    /// Persists immediately when a conversation row exists; otherwise the
    /// selection is captured on the first send via <see cref="InitializeConversationIfNeeded"/>.
    /// </summary>
    public void SaveActivePersona(string? personaId)
    {
        ActivePersonaId = string.IsNullOrEmpty(personaId) ? null : personaId;
        if (_conversationRepo is null || string.IsNullOrEmpty(ConversationId)) return;
        var existing = _conversationRepo.Get(ConversationId!);
        if (existing is null) return;
        _conversationRepo.Upsert(existing with { PersonaId = ActivePersonaId });

        // Push the new persona label into the sidebar so the BYOK badge
        // refreshes without requiring a user message to be sent first.
        // Pass "" (not null) when un-binding so the sidebar treats it as
        // an explicit clear rather than "no info, keep existing".
        ConversationTouched?.Invoke(this, new ConversationTouchedEventArgs(
            ConversationId!,
            ConversationTitle,
            DateTimeOffset.FromUnixTimeMilliseconds(existing.UpdatedAt),
            existing.ProviderId,
            ActivePersonaId is null ? "" : ActivePersona?.Name));
    }

    /// <summary>
    /// Set whether the conversation-level prompt overrides or appends to the
    /// persona prompt. Accepts "override" / "append" — anything else falls
    /// back to "override".
    /// </summary>
    public void SaveSystemPromptMode(string? mode)
    {
        SystemPromptMode = string.Equals(mode, "append", StringComparison.OrdinalIgnoreCase) ? "append" : "override";
        if (_conversationRepo is null || string.IsNullOrEmpty(ConversationId)) return;
        var existing = _conversationRepo.Get(ConversationId!);
        if (existing is null) return;
        _conversationRepo.Upsert(existing with { SystemPromptMode = SystemPromptMode });
    }

    public void StartDraftConversation()
    {
        _messageLoadVersion++;
        foreach (var existing in Messages) existing.Dispose();
        Messages.Clear();
        _pendingOlderMessages.Clear();
        ConversationId = null;
        ConversationTitle = "新对话";
        ConversationSystemPrompt = null;
        ActivePersonaId = ResolveDefaultPersonaId();
        SystemPromptMode = "override";
        ContextGauge.Reset();
        // New conversation has no working directory yet — clear artifacts
        // and dismiss the panel so the previous conversation's files don't stick.
        RefreshArtifacts();
    }

    private string? ResolveDefaultPersonaId() =>
        _personas?.Find(PersonaListViewModel.BuiltinDefaultId) is not null
            ? PersonaListViewModel.BuiltinDefaultId
            : null;

    public async Task LoadConversationAsync(string conversationId, bool loadAllMessagesImmediately = false)
    {
        ConversationId = conversationId;
        // Cleared here and restored from the loaded messages below. Leaving it
        // cleared was the first attempt and it was wrong: reopening a conversation
        // made the gauge vanish until the user sent another turn, which reads as the
        // feature being broken rather than as "not measured yet".
        ContextGauge.Reset();
        var loadVersion = ++_messageLoadVersion;
        var loadUiContext = SynchronizationContext.Current;

        // Show the loading overlay for the whole load. The overlay's first
        // paint is forced synchronously by the Desktop layer BEFORE this method
        // runs its heavy work (see MainWindow.ConversationListBox_SelectionChanged),
        // because a flag flipped here can't paint while the UI thread is busy
        // building the FlowDocument. A fast (small) load finishes within a frame
        // so the overlay barely registers; its fade-in smooths the rare flash.
        IsConversationLoading = true;

        void FinishLoadingIndicator()
        {
            // Defer the hide to the back of the dispatcher queue so the first
            // batch of messages gets a layout/paint pass before the overlay
            // clears — otherwise it could vanish a frame before content shows.
            if (loadUiContext is not null)
                loadUiContext.Post(_ => { if (loadVersion == _messageLoadVersion) IsConversationLoading = false; }, null);
            else
                IsConversationLoading = false;
        }

        try
        {
            // Dispose any existing message VMs (their elapsed timers etc.)
            // before clearing the collection.
            foreach (var existing in Messages) existing.Dispose();
            Messages.Clear();
            _pendingOlderMessages.Clear();

            ConversationRow? conversationRow = null;
            if (_messageRepo is not null)
            {
                var readSw = System.Diagnostics.Stopwatch.StartNew();
                var snapshot = await Task.Run(() =>
                {
                    var messages = PrepareMessageSnapshot(_messageRepo.List(conversationId));
                    var conversation = _conversationRepo?.Get(conversationId);
                    return (messages, conversation);
                }).ConfigureAwait(true);
                PerfTrace?.Invoke("load.read+meta",
                    $"{readSw.Elapsed.TotalMilliseconds:N0} ms  msgs={snapshot.messages.Count}");

                if (loadVersion != _messageLoadVersion || ConversationId != conversationId)
                    return;

                conversationRow = snapshot.conversation;
                var prepared = snapshot.messages;

                // From the whole snapshot, not just the materialized tail: the
                // reading belongs to the conversation, and only the newest turns are
                // built up front.
                RestoreContextGauge(prepared);

                // Open at the END of the conversation. The newest messages are
                // what the user clicked to see, and materializing only those
                // keeps the cost of opening a 500-message conversation
                // proportional to the viewport instead of to the history —
                // every message we build here is a full markdown parse and
                // FlowDocument, on the UI thread. The rest waits in
                // _pendingOlderMessages until the user scrolls up.
                var materialized = new List<MessageViewModel>();
                if (loadAllMessagesImmediately)
                {
                    foreach (var message in prepared)
                        materialized.Add(CreateMessageViewModel(message));
                }
                else
                {
                    var tailStart = Math.Max(0, prepared.Count - TailBatch);
                    for (int i = tailStart; i < prepared.Count; i++)
                        materialized.Add(CreateMessageViewModel(prepared[i]));
                    if (tailStart > 0)
                        _pendingOlderMessages.AddRange(prepared.GetRange(0, tailStart));
                }
                _messages.ReplaceAll(materialized);
                OnPropertyChanged(nameof(HasOlderMessages));
                UpdateLatestAssistantFlags();
                PerfTrace?.Invoke("load.materialize",
                    $"{Messages.Count} shown, {_pendingOlderMessages.Count} parked");
            }

            conversationRow ??= _conversationRepo?.Get(conversationId);
            if (conversationRow is { } row2)
            {
                ConversationTitle = string.IsNullOrWhiteSpace(row2.Title) ? "新对话" : row2.Title;
                ConversationSystemPrompt = row2.SystemPrompt;
                ActivePersonaId = row2.PersonaId;
                SystemPromptMode = string.Equals(row2.SystemPromptMode, "append", StringComparison.OrdinalIgnoreCase)
                    ? "append" : "override";
                RestoreActiveModel(row2);
            }
            else
            {
                ConversationTitle = "新对话";
                ConversationSystemPrompt = null;
                ActivePersonaId = null;
                SystemPromptMode = "override";
            }

            // Surface any artifacts already sitting in this conversation's
            // working directory (from earlier python runs / uploads).
            RefreshArtifacts();
        }
        finally
        {
            // Covers success, the stale-version early return, and exceptions.
            // The deferred Post re-checks the load version, so a superseded
            // load never hides a newer load's indicator.
            FinishLoadingIndicator();
        }
    }

    private static List<PreparedMessage> PrepareMessageSnapshot(IReadOnlyList<MessageRow> rows)
    {
        var prepared = new List<PreparedMessage>(rows.Count);
        IReadOnlyList<SourceReference>? lastKnownSources = null;

        // Every retry attempt carries a full copy of that answer's body, so a
        // message the user regenerated a few times can hold megabytes of meta —
        // measured at 7.6 MB of attempts against 3.1 MB of actual content on one
        // deepresearch answer. Materializing all of it on load is pure waste:
        // MessageViewModel.HasRetryBar gates the attempt switcher on
        // IsLatestAssistant, so no older message can ever display them.
        //
        // Parse them for the newest assistant row only. Nothing writes meta back
        // for older rows either — UpdatePersistedMessage runs on the user's own
        // message or on the assistant turn currently being generated — so the
        // rows we skip keep their stored history untouched.
        var latestAssistantIndex = -1;
        for (var i = rows.Count - 1; i >= 0; i--)
        {
            if (rows[i].Role == ChatMessage.RoleAssistant)
            {
                latestAssistantIndex = i;
                break;
            }
        }

        for (var index = 0; index < rows.Count; index++)
        {
            var row = rows[index];
            var split = SplitInlineThinking(row.Content);
            string? modelLabel = null;
            string? providerLabel = null;
            string? thinkingText = split.Thinking;
            Usage? usage = null;
            IReadOnlyList<SourceReference>? sources = null;
            IReadOnlyList<AttachmentChip>? attachments = null;
            string? contentPartsJson = null;
            IReadOnlyList<MessageAttempt>? retryAttempts = null;
            IReadOnlyList<ToolCallDelta>? toolCalls = null;
            IReadOnlyList<ThinkingSegmentDelta>? thinkingSegments = null;
            var retryCurrent = 0;
            var wasStopped = false;
            var contextTokens = 0;
            var contextWindow = 0;
            var compactionTokensBefore = 0;
            var compactionTokensAfter = 0;
            string? compactionReason = null;
            if (!string.IsNullOrEmpty(row.Meta))
            {
                try
                {
                    using var doc = JsonDocument.Parse(row.Meta);
                    if (doc.RootElement.TryGetProperty("model", out var m) && m.ValueKind == JsonValueKind.String)
                        modelLabel = m.GetString();
                    if (doc.RootElement.TryGetProperty("provider", out var p) && p.ValueKind == JsonValueKind.String)
                        providerLabel = p.GetString();
                    if (doc.RootElement.TryGetProperty("thinking", out var th) && th.ValueKind == JsonValueKind.String)
                    {
                        var thinking = th.GetString();
                        if (!string.IsNullOrWhiteSpace(thinking))
                            thinkingText = MergeThinking(thinking, thinkingText);
                    }
                    usage = ParseUsage(doc.RootElement, "response_stats");
                    sources = ParseSources(doc.RootElement);
                    attachments = ParseAttachments(doc.RootElement);
                    contentPartsJson = ParseContentPartsJson(doc.RootElement);
                    if (index == latestAssistantIndex)
                        (retryAttempts, retryCurrent) = ParseRetry(doc.RootElement);
                    toolCalls = ParseToolCalls(doc.RootElement);
                    thinkingSegments = ParseThinkingSegments(doc.RootElement);
                    (toolCalls, thinkingSegments) = InferMissingTimelineIndexes(toolCalls, thinkingSegments);
                    retryAttempts = RestoreCurrentRetryAttemptState(
                        retryAttempts,
                        retryCurrent,
                        thinkingText,
                        thinkingSegments,
                        toolCalls);
                    wasStopped = doc.RootElement.TryGetProperty("stopped", out var st)
                                 && st.ValueKind == JsonValueKind.True;
                    contextTokens = ReadMetaInt(doc.RootElement, "context_tokens");
                    contextWindow = ReadMetaInt(doc.RootElement, "context_window");
                    compactionTokensBefore = ReadMetaInt(doc.RootElement, "compaction_tokens_before");
                    compactionTokensAfter = ReadMetaInt(doc.RootElement, "compaction_tokens_after");
                    compactionReason = ReadString(doc.RootElement, "compaction_reason");
                }
                catch (JsonException) { }
            }

            if (row.Role == ChatMessage.RoleAssistant && sources is { Count: > 0 })
                lastKnownSources = sources;
            else if (row.Role == ChatMessage.RoleAssistant
                     && sources is null
                     && lastKnownSources is { Count: > 0 }
                     && row.Content.Contains("<ref", StringComparison.OrdinalIgnoreCase))
                sources = lastKnownSources;

            var visibleContent = split.Visible;
            if (row.Role == ChatMessage.RoleAssistant)
            {
                var rewriteContexts = new List<PythonArtifactMarkdownRewriter.ArtifactContext>(
                    PythonArtifactMarkdownRewriter.CreateContexts(toolCalls));
                // Resolve inline BYOK generate_image links (![](generated-image-1.png))
                // to the real local attachment file so they render and can be zoomed.
                var imageContext = PythonArtifactMarkdownRewriter.CreateAttachmentContext(attachments);
                if (imageContext is not null)
                    rewriteContexts.Add(imageContext);
                visibleContent = PythonArtifactMarkdownRewriter.Rewrite(visibleContent, rewriteContexts);
            }

            prepared.Add(new PreparedMessage(
                row.Id,
                row.Role,
                visibleContent,
                thinkingText,
                row.CreatedAt,
                modelLabel,
                providerLabel,
                usage,
                sources,
                attachments,
                contentPartsJson,
                retryAttempts,
                retryCurrent,
                toolCalls,
                thinkingSegments,
                wasStopped,
                contextTokens,
                contextWindow,
                compactionTokensBefore,
                compactionReason,
                compactionTokensAfter));
        }

        return prepared;
    }

    private MessageViewModel CreateMessageViewModel(PreparedMessage prepared)
    {
        var vm = new MessageViewModel(prepared.Role, prepared.Content, DateTimeOffset.FromUnixTimeMilliseconds(prepared.CreatedAt))
        {
            MessageId = prepared.Id,
            ModelLabel = prepared.ModelLabel,
            ProviderLabel = prepared.ProviderLabel,
            Usage = prepared.Usage,
            Sources = prepared.Sources,
            Attachments = prepared.Attachments,
            ContentPartsJson = prepared.ContentPartsJson,
            RetryAttempts = prepared.RetryAttempts,
            RetryCurrentIndex = prepared.RetryCurrentIndex,
            WasStopped = prepared.WasStopped,
            ContextTokens = prepared.ContextTokens,
            ContextWindow = prepared.ContextWindow,
            CompactionTokensBefore = prepared.CompactionTokensBefore,
            CompactionReason = prepared.CompactionReason,
            CompactionTokensAfter = prepared.CompactionTokensAfter,
            AutoCollapseThinkingOnComplete = AutoCollapseThinking
        };
        if (prepared.ToolCalls is { Count: > 0 })
        {
            foreach (var toolCall in prepared.ToolCalls)
                vm.ApplyToolDelta(toolCall);
        }
        if (!string.IsNullOrWhiteSpace(prepared.Thinking))
        {
            vm.Thinking = prepared.Thinking;
            vm.ThinkingElapsedSeconds = 0;
            vm.IsThinkingActive = false;
            vm.RestoreThinkingSegments(prepared.ThinkingSegments is { Count: > 0 }
                ? prepared.ThinkingSegments
                : [new ThinkingSegmentDelta(prepared.Thinking, 0)]);
        }
        return vm;
    }

    private sealed record PreparedMessage(
        string Id,
        string Role,
        string Content,
        string? Thinking,
        long CreatedAt,
        string? ModelLabel,
        string? ProviderLabel,
        Usage? Usage,
        IReadOnlyList<SourceReference>? Sources,
        IReadOnlyList<AttachmentChip>? Attachments,
        string? ContentPartsJson,
        IReadOnlyList<MessageAttempt>? RetryAttempts,
        int RetryCurrentIndex,
        IReadOnlyList<ToolCallDelta>? ToolCalls,
        IReadOnlyList<ThinkingSegmentDelta>? ThinkingSegments,
        bool WasStopped,
        int ContextTokens = 0,
        int ContextWindow = 0,
        int CompactionTokensBefore = 0,
        string? CompactionReason = null,
        int CompactionTokensAfter = 0);

    /// <summary>
    /// Materialize up to <paramref name="count"/> more of the history parked by
    /// <see cref="LoadConversationAsync"/>, prepending it to <see cref="Messages"/>
    /// in chronological order. Returns how many messages were actually inserted
    /// (0 once the whole conversation is loaded).
    /// </summary>
    /// <remarks>
    /// Callers own the scroll position. Prepending grows the scroll extent
    /// above the viewport, so without compensation the content the user is
    /// reading gets shoved down the screen by however tall the new messages
    /// turn out to be.
    /// </remarks>
    public int LoadOlderMessages(int count)
    {
        if (count <= 0 || _pendingOlderMessages.Count == 0) return 0;

        // Take from the tail: _pendingOlderMessages is chronological, so its
        // last entries are the ones immediately preceding Messages[0].
        var take = Math.Min(count, _pendingOlderMessages.Count);
        var start = _pendingOlderMessages.Count - take;
        for (int i = 0; i < take; i++)
            Messages.Insert(i, CreateMessageViewModel(_pendingOlderMessages[start + i]));
        _pendingOlderMessages.RemoveRange(start, take);

        OnPropertyChanged(nameof(HasOlderMessages));
        return take;
    }

    public void AppendUserMessage(
        string text,
        IReadOnlyList<AttachmentChip>? attachments = null,
        string? contentPartsJson = null)
    {
        EnsureConversationExists(text);
        var vm = new MessageViewModel(ChatMessage.RoleUser, text, DateTimeOffset.UtcNow)
        {
            Attachments = attachments,
            ContentPartsJson = contentPartsJson
        };
        Messages.Add(vm);
        PersistMessage(vm);
        TouchConversation();
    }

    public MessageViewModel BeginAssistantMessage()
    {
        EnsureConversationExists();
        var vm = new MessageViewModel(ChatMessage.RoleAssistant, string.Empty, DateTimeOffset.UtcNow)
        {
            IsStreaming = true,
            ModelLabel = ActiveModel?.DisplayName,
            ProviderLabel = ActiveProvider?.DisplayName,
            AutoCollapseThinkingOnComplete = AutoCollapseThinking
        };
        vm.StartPending(IsRoutesModel(ActiveModel));
        Messages.Add(vm);
        return vm;
    }

    public void FinalizeAssistantMessage(MessageViewModel vm)
    {
        vm.StopPending();
        vm.FlushPendingDelta();
        vm.IsStreaming = false;
        vm.StopThinking();
        PersistMessage(vm);
        TouchConversation();
    }

    public void FinalizeAssistantMessage(string conversationId, MessageViewModel vm)
    {
        if (string.IsNullOrWhiteSpace(conversationId))
        {
            FinalizeAssistantMessage(vm);
            return;
        }

        vm.StopPending();
        vm.FlushPendingDelta();
        vm.IsStreaming = false;
        vm.StopThinking();
        PersistMessage(vm, conversationId);
        TouchConversation(conversationId);

        if (ConversationId == conversationId && !Messages.Contains(vm))
        {
            Messages.Add(vm);
            UpdateLatestAssistantFlags();
        }
    }

    public void DetachTransientMessage(MessageViewModel vm)
    {
        if (Messages.Remove(vm))
            UpdateLatestAssistantFlags();
    }

    public void AttachTransientMessage(MessageViewModel vm)
    {
        if (Messages.Contains(vm)) return;

        // A regenerated message already exists in the store, so loading the
        // conversation on the way back rebuilt it from the row — which still holds
        // the attempt being replaced. The streaming instance is the live one; it
        // takes that copy's place instead of appearing next to it.
        if (!string.IsNullOrWhiteSpace(vm.MessageId))
        {
            var stale = Messages.FirstOrDefault(m =>
                string.Equals(m.MessageId, vm.MessageId, StringComparison.Ordinal));
            if (stale is not null)
            {
                var at = Messages.IndexOf(stale);
                Messages.RemoveAt(at);
                Messages.Insert(at, vm);
                UpdateLatestAssistantFlags();
                return;
            }
        }

        Messages.Add(vm);
        UpdateLatestAssistantFlags();
    }

    /// <summary>
    /// Finish an assistant message that is already in the store — a retry.
    ///
    /// The difference from <see cref="FinalizeAssistantMessage(string, MessageViewModel)"/>
    /// is the persistence verb: that one inserts, which for a regenerated answer
    /// would leave two rows for one bubble. Touching the conversation still matters
    /// though — cloud sync picks work up by <c>updated_at</c>, and updating a
    /// message row alone does not move it, so without this the server keeps serving
    /// the attempt the user threw away.
    /// </summary>
    public void CompleteRetriedAssistantMessage(string conversationId, MessageViewModel vm)
    {
        vm.StopPending();
        vm.FlushPendingDelta();
        vm.IsStreaming = false;
        vm.StopThinking();
        UpdatePersistedMessage(vm);

        if (string.IsNullOrWhiteSpace(conversationId)) TouchConversation();
        else TouchConversation(conversationId);
    }

    public void ApplyExternalConversationTitle(string conversationId, string title)
    {
        if (string.IsNullOrWhiteSpace(conversationId) || string.IsNullOrWhiteSpace(title))
            return;

        var updatedAt = DateTimeOffset.UtcNow;
        if (_conversationRepo?.Get(conversationId) is { } row)
            updatedAt = DateTimeOffset.FromUnixTimeMilliseconds(row.UpdatedAt);

        if (ConversationId == conversationId)
            ConversationTitle = title;

        var existingRow = _conversationRepo?.Get(conversationId);
        var providerId = existingRow?.ProviderId;
        ConversationTouched?.Invoke(this, new ConversationTouchedEventArgs(
            conversationId, title, updatedAt, providerId,
            _personas?.Find(existingRow?.PersonaId)?.Name));
    }

    private void PersistMessage(MessageViewModel vm)
    {
        if (string.IsNullOrEmpty(ConversationId)) return;
        PersistMessage(vm, ConversationId!);
    }

    private void PersistMessage(MessageViewModel vm, string conversationId)
    {
        if (_messageRepo is null || string.IsNullOrEmpty(conversationId)) return;
        var meta = BuildMessageMeta(vm);
        var id = Guid.NewGuid().ToString("N");
        _messageRepo.Insert(new MessageRow(
            Id: id,
            ConversationId: conversationId,
            Role: vm.Role,
            Content: vm.Content,
            Meta: meta,
            CreatedAt: vm.Timestamp.ToUnixTimeMilliseconds()));
        vm.MessageId = id;
    }

    public void UpdatePersistedMessage(MessageViewModel vm)
    {
        if (_messageRepo is null || string.IsNullOrWhiteSpace(vm.MessageId)) return;
        _messageRepo.Update(vm.MessageId, vm.Content, BuildMessageMeta(vm));
    }

    /// <summary>
    /// Mark a user-requested compaction where it actually happened.
    ///
    /// An automatic compaction arrives mid-turn and is recorded on the message being
    /// streamed. A manual one has no turn to ride on, so nothing was writing it down
    /// at all: the gauge held it, and the gauge is rebuilt empty on every load — which
    /// is why reopening the conversation restored the pre-compaction reading from the
    /// last turn as if nothing had been cut.
    ///
    /// It lands on the newest assistant message, the last thing the model wrote before
    /// its history was summarized. A turn still streaming has no row yet; leaving the
    /// property set is enough, because <see cref="FinalizeAssistantMessage(MessageViewModel)"/>
    /// writes the marker along with everything else.
    /// </summary>
    public void NoteManualCompaction(ContextGaugeViewModel.CompactionSizes sizes)
    {
        if (sizes.TokensBefore <= 0) return;

        var target = Messages.LastOrDefault(m =>
            string.Equals(m.Role, ChatMessage.RoleAssistant, StringComparison.OrdinalIgnoreCase));
        if (target is null) return;

        target.NoteCompaction(
            sizes.TokensBefore,
            sizes.TokensAfter,
            MessageViewModel.ManualCompactionReason);
        if (string.IsNullOrWhiteSpace(target.MessageId)) return;

        UpdatePersistedMessage(target);
        // Cloud sync picks work up by updated_at, and updating a message row alone
        // does not move it.
        TouchConversation();
    }

    private static string BuildMessageMeta(MessageViewModel vm)
    {
        var meta = new JsonObject();
        if (!string.IsNullOrWhiteSpace(vm.ModelLabel)) meta["model"] = vm.ModelLabel;
        if (!string.IsNullOrWhiteSpace(vm.ProviderLabel)) meta["provider"] = vm.ProviderLabel;
        if (!string.IsNullOrWhiteSpace(vm.Thinking)) meta["thinking"] = vm.Thinking;
        if (vm.WasStopped) meta["stopped"] = true;
        if (vm.Usage is not null)
        {
            meta["response_stats"] = BuildUsageJson(vm.Usage);
        }
        // Separate from response_stats: that is the turn's cost, this is how full
        // the context was left. Persisted so reopening a conversation restores the
        // gauge instead of blanking it until the next turn.
        if (vm.ContextTokens > 0) meta["context_tokens"] = vm.ContextTokens;
        if (vm.ContextWindow > 0) meta["context_window"] = vm.ContextWindow;
        if (vm.CompactionTokensBefore > 0) meta["compaction_tokens_before"] = vm.CompactionTokensBefore;
        if (vm.CompactionTokensAfter > 0) meta["compaction_tokens_after"] = vm.CompactionTokensAfter;
        if (!string.IsNullOrWhiteSpace(vm.CompactionReason)) meta["compaction_reason"] = vm.CompactionReason;
        if (vm.Sources is { Count: > 0 })
        {
            meta["sources"] = new JsonArray(vm.Sources
                .Select(s => new JsonObject
                {
                    ["id"] = s.Id,
                    ["title"] = s.Title,
                    ["url"] = s.Url
                })
                .Cast<JsonNode?>()
                .ToArray());
        }
        if (vm.Attachments is { Count: > 0 })
        {
            meta["attachments"] = new JsonArray(vm.Attachments
                .Select(a =>
                {
                    var obj = new JsonObject
                    {
                        ["filename"] = a.FileName,
                        ["label"] = a.Label
                    };
                    if (!string.IsNullOrWhiteSpace(a.ThumbnailUrl))
                        obj["thumbnailUrl"] = a.ThumbnailUrl;
                    if (!string.IsNullOrWhiteSpace(a.LocalName))
                        obj["localName"] = a.LocalName;
                    if (!string.IsNullOrWhiteSpace(a.MimeType))
                        obj["mime"] = a.MimeType;
                    if (a.Kind is { } kind)
                        obj["kind"] = kind == AttachmentKind.Image ? "image" : "file";
                    if (!string.IsNullOrWhiteSpace(a.WorkspacePath))
                        obj["workspacePath"] = a.WorkspacePath;
                    if (!string.IsNullOrWhiteSpace(a.ExtractedTextPath))
                        obj["textPath"] = a.ExtractedTextPath;
                    return obj;
                })
                .Cast<JsonNode?>()
                .ToArray());
        }
        if (!string.IsNullOrWhiteSpace(vm.ContentPartsJson))
        {
            try
            {
                if (JsonNode.Parse(vm.ContentPartsJson!) is JsonNode parts)
                    meta["content_parts"] = parts;
            }
            catch (JsonException) { }
        }
        if (vm.RetryAttempts is { Count: > 1 })
        {
            meta["retry"] = new JsonObject
            {
                ["current"] = vm.RetryCurrentIndex,
                ["attempts"] = new JsonArray(vm.RetryAttempts
                    .Select(BuildRetryAttemptJson)
                    .Cast<JsonNode?>()
                    .ToArray())
            };
        }
        if (vm.ToolCalls.Count > 0)
        {
            meta["tool_calls"] = new JsonArray(vm.ToolCalls
                .Select(t => new JsonObject
                {
                    ["id"] = t.Id,
                    ["name"] = t.Name,
                    ["status"] = t.Status,
                    ["label"] = t.Label,
                    ["summary"] = t.Summary,
                    ["detail"] = t.Detail,
                    ["arguments_json"] = t.ArgumentsJson,
                    ["result_preview_json"] = t.ResultPreviewJson,
                    ["provider"] = t.Provider,
                    ["content_offset"] = t.ContentOffset,
                    ["timeline_index"] = t.TimelineIndex
                })
                .Cast<JsonNode?>()
                .ToArray());
        }
        if (vm.ThinkingSegments.Count > 0)
        {
            meta["thinking_segments"] = new JsonArray(vm.ThinkingSegments
                .Where(t => !string.IsNullOrWhiteSpace(t.Source))
                .Select(t => new JsonObject
                {
                    ["source"] = t.Source,
                    ["content_offset"] = t.ContentOffset,
                    ["timeline_index"] = t.TimelineIndex,
                    ["elapsed_seconds"] = t.ElapsedSeconds
                })
                .Cast<JsonNode?>()
                .ToArray());
        }
        return meta.ToJsonString();
    }

    private static JsonObject BuildUsageJson(Usage usage)
    {
        var obj = new JsonObject();
        if (usage.PromptTokens is { } prompt) obj["promptTokens"] = prompt;
        if (usage.CompletionTokens is { } completion)
        {
            obj["completionTokens"] = completion;
            obj["answerTokens"] = completion;
        }
        if (usage.TotalTokens is { } total) obj["totalTokens"] = total;
        return obj;
    }

    private static JsonArray BuildSourcesJson(IReadOnlyList<SourceReference> sources) =>
        new(sources
            .Select(s => new JsonObject
            {
                ["id"] = s.Id,
                ["title"] = s.Title,
                ["url"] = s.Url
            })
            .Cast<JsonNode?>()
            .ToArray());

    private static JsonObject BuildRetryAttemptJson(MessageAttempt attempt)
    {
        var result = new JsonObject
        {
            ["content"] = attempt.Content,
            ["model_label"] = attempt.ModelLabel,
            ["response_stats"] = attempt.Usage is null ? (JsonNode?)null : BuildUsageJson(attempt.Usage),
            ["sources"] = attempt.Sources is null ? (JsonNode?)null : BuildSourcesJson(attempt.Sources),
            ["stopped"] = attempt.WasStopped ? true : (JsonNode?)null
        };
        if (!string.IsNullOrWhiteSpace(attempt.Thinking))
            result["thinking"] = attempt.Thinking;
        if (attempt.ToolCalls is { Count: > 0 })
        {
            result["tool_calls"] = new JsonArray(attempt.ToolCalls
                .Select(tool => new JsonObject
                {
                    ["id"] = tool.Id,
                    ["name"] = tool.Name,
                    ["status"] = tool.Status,
                    ["label"] = tool.Label,
                    ["summary"] = tool.Summary,
                    ["detail"] = tool.Detail,
                    ["arguments_json"] = tool.ArgumentsJson,
                    ["result_preview_json"] = tool.ResultPreviewJson,
                    ["provider"] = tool.Provider,
                    ["content_offset"] = tool.ContentOffset,
                    ["timeline_index"] = tool.TimelineIndex
                })
                .Cast<JsonNode?>()
                .ToArray());
        }
        if (attempt.ThinkingSegments is { Count: > 0 })
        {
            result["thinking_segments"] = new JsonArray(attempt.ThinkingSegments
                .Where(segment => !string.IsNullOrWhiteSpace(segment.Source))
                .Select(segment => new JsonObject
                {
                    ["source"] = segment.Source,
                    ["content_offset"] = segment.ContentOffset,
                    ["timeline_index"] = segment.TimelineIndex,
                    ["elapsed_seconds"] = segment.ElapsedSeconds
                })
                .Cast<JsonNode?>()
                .ToArray());
        }
        return result;
    }

    private void EnsureConversationExists(string? firstUserText = null)
    {
        if (_conversationRepo is null || string.IsNullOrEmpty(ConversationId)) return;
        if (_conversationRepo.Get(ConversationId!) is not null) return;

        var now = DateTimeOffset.UtcNow.ToUnixTimeMilliseconds();
        var title = string.IsNullOrWhiteSpace(firstUserText) ? "无标题对话" : GenerateTitle(firstUserText);
        _conversationRepo.Upsert(new ConversationRow(
            Id: ConversationId!,
            Title: title,
            ModelId: ActiveModel?.Id,
            ProviderId: ActiveProvider?.Id,
            CreatedAt: now,
            UpdatedAt: now,
            Pinned: false,
            DeletedAt: null,
            SystemPrompt: ConversationSystemPrompt,
            PersonaId: ActivePersonaId,
            SystemPromptMode: SystemPromptMode == "append" ? "append" : null));
        ConversationTitle = title;
        ConversationTouched?.Invoke(this, new ConversationTouchedEventArgs(
            ConversationId!, title, DateTimeOffset.FromUnixTimeMilliseconds(now), ActiveProvider?.Id, ActivePersona?.Name));
    }

    private void TouchConversation()
    {
        if (_conversationRepo is null || string.IsNullOrEmpty(ConversationId)) return;
        var existing = _conversationRepo.Get(ConversationId!);
        if (existing is null) return;
        var now = DateTimeOffset.UtcNow.ToUnixTimeMilliseconds();
        var firstUser = Messages.FirstOrDefault(m => m.Role == ChatMessage.RoleUser);
        var title = !string.IsNullOrWhiteSpace(existing.Title) && existing.Title != "新对话"
            ? existing.Title
            : (firstUser is null ? "无标题对话" : GenerateTitle(firstUser.Content));
        _conversationRepo.Upsert(existing with
        {
            Title = title,
            UpdatedAt = now,
            ModelId = ActiveModel?.Id,
            ProviderId = ActiveProvider?.Id
        });
        ConversationTitle = title;
        ConversationTouched?.Invoke(this, new ConversationTouchedEventArgs(
            ConversationId!, title, DateTimeOffset.FromUnixTimeMilliseconds(now), ActiveProvider?.Id, ActivePersona?.Name));
    }

    private void TouchConversation(string conversationId)
    {
        if (_conversationRepo is null || string.IsNullOrEmpty(conversationId)) return;
        var existing = _conversationRepo.Get(conversationId);
        if (existing is null) return;

        var now = DateTimeOffset.UtcNow.ToUnixTimeMilliseconds();
        var title = string.IsNullOrWhiteSpace(existing.Title) ? "无标题对话" : existing.Title;
        _conversationRepo.Upsert(existing with
        {
            Title = title,
            UpdatedAt = now
        });

        if (ConversationId == conversationId)
            ConversationTitle = title;

        ConversationTouched?.Invoke(this, new ConversationTouchedEventArgs(
            conversationId, title, DateTimeOffset.FromUnixTimeMilliseconds(now), existing.ProviderId,
            _personas?.Find(existing.PersonaId)?.Name));
    }

    private void RestoreActiveModel(ConversationRow row)
    {
        if (HasSavedModel(row))
        {
            if (!SetActiveByIds(row.ProviderId, row.ModelId, ignoreConversationBoundary: true))
            {
                ActiveProvider = null;
                ActiveModel = null;
            }
            return;
        }

        TryAutoPickActive();
    }

    private void RefreshActiveModelAfterProviderChange()
    {
        if (!IsActiveModelAvailable())
        {
            ActiveProvider = null;
            ActiveModel = null;
        }

        if (!TryRestoreActiveModelForCurrentConversation())
            TryAutoPickActive();
    }

    private bool TryRestoreActiveModelForCurrentConversation()
    {
        if (_conversationRepo is null || string.IsNullOrWhiteSpace(ConversationId))
            return false;

        var row = _conversationRepo.Get(ConversationId);
        if (row is null) return false;
        if (!HasSavedModel(row)) return false;
        if (SetActiveByIds(row.ProviderId, row.ModelId, ignoreConversationBoundary: true)) return true;

        ActiveProvider = null;
        ActiveModel = null;
        return true;
    }

    private bool IsActiveModelAvailable()
    {
        if (ActiveProvider is null || ActiveModel is null) return false;
        if (!CanSwitchToProvider(ActiveProvider)) return false;
        var resolved = _providers.FindModel(ActiveProvider.Id, ActiveModel.Id);
        return resolved is not null;
    }

    private static bool HasSavedModel(ConversationRow row) =>
        !string.IsNullOrWhiteSpace(row.ProviderId)
        && !string.IsNullOrWhiteSpace(row.ModelId);

    private ConversationProviderFamily? GetCurrentConversationProviderFamily()
    {
        if (_conversationRepo is null || string.IsNullOrWhiteSpace(ConversationId))
            return null;

        var row = _conversationRepo.Get(ConversationId);
        return GetProviderFamily(row?.ProviderId);
    }

    private static ConversationProviderFamily? GetProviderFamily(string? providerId)
    {
        if (string.IsNullOrWhiteSpace(providerId)) return null;
        // Chat (proxy) is its own family; local-tools (Work) and BYOK share the
        // local-agent family so a conversation can move freely between them.
        return string.Equals(providerId, MolaGptProviderIds.Proxy, StringComparison.OrdinalIgnoreCase)
            ? ConversationProviderFamily.Chat
            : ConversationProviderFamily.Agent;
    }

    private enum ConversationProviderFamily
    {
        Chat,
        Agent
    }

    private void UpdateLatestAssistantFlags()
    {
        MessageViewModel? latest = null;
        foreach (var message in Messages)
        {
            if (message.Role == ChatMessage.RoleAssistant)
                latest = message;
        }

        foreach (var message in Messages)
            message.IsLatestAssistant = ReferenceEquals(message, latest);
    }

    private static IReadOnlyList<SourceReference>? ParseSources(JsonElement root)
    {
        if (!root.TryGetProperty("sources", out var node) || node.ValueKind != JsonValueKind.Array)
            return null;

        var list = new List<SourceReference>();
        var fallbackId = 1;
        foreach (var item in node.EnumerateArray())
        {
            if (item.ValueKind != JsonValueKind.Object) continue;
            var id = item.TryGetProperty("id", out var idNode)
                     && idNode.ValueKind == JsonValueKind.Number
                     && idNode.TryGetInt32(out var parsedId)
                ? parsedId
                : fallbackId;
            var title = item.TryGetProperty("title", out var titleNode) && titleNode.ValueKind == JsonValueKind.String
                ? titleNode.GetString() ?? string.Empty
                : string.Empty;
            var url = item.TryGetProperty("url", out var urlNode) && urlNode.ValueKind == JsonValueKind.String
                ? urlNode.GetString() ?? string.Empty
                : string.Empty;
            list.Add(new SourceReference(id, title, url));
            fallbackId++;
        }

        return list.Count == 0 ? null : list;
    }

    private static IReadOnlyList<AttachmentChip>? ParseAttachments(JsonElement root)
    {
        if (!root.TryGetProperty("attachments", out var node) || node.ValueKind != JsonValueKind.Array)
            return null;

        var list = new List<AttachmentChip>();
        foreach (var item in node.EnumerateArray())
        {
            if (item.ValueKind != JsonValueKind.Object) continue;
            var filename = item.TryGetProperty("filename", out var filenameNode)
                           && filenameNode.ValueKind == JsonValueKind.String
                ? filenameNode.GetString()
                : null;
            if (string.IsNullOrWhiteSpace(filename)) continue;
            var label = item.TryGetProperty("label", out var labelNode)
                        && labelNode.ValueKind == JsonValueKind.String
                ? labelNode.GetString()
                : null;
            var thumbnailUrl = item.TryGetProperty("thumbnailUrl", out var thumbNode)
                               && thumbNode.ValueKind == JsonValueKind.String
                ? thumbNode.GetString()
                : null;
            var localName = item.TryGetProperty("localName", out var localNode)
                            && localNode.ValueKind == JsonValueKind.String
                ? localNode.GetString()
                : null;
            var mime = item.TryGetProperty("mime", out var mimeNode)
                       && mimeNode.ValueKind == JsonValueKind.String
                ? mimeNode.GetString()
                : null;
            var kind = item.TryGetProperty("kind", out var kindNode) && kindNode.ValueKind == JsonValueKind.String
                ? kindNode.GetString() switch
                {
                    "image" => AttachmentKind.Image,
                    "file" => AttachmentKind.File,
                    _ => (AttachmentKind?)null
                }
                : null;
            list.Add(new AttachmentChip(filename!, string.IsNullOrWhiteSpace(label) ? "附件" : label!, thumbnailUrl)
            {
                LocalName = localName,
                MimeType = mime,
                Kind = kind,
                WorkspacePath = ReadOptionalString(item, "workspacePath"),
                ExtractedTextPath = ReadOptionalString(item, "textPath")
            });
        }

        return list.Count == 0 ? null : list;
    }

    private static string? ReadOptionalString(JsonElement owner, string propertyName) =>
        owner.TryGetProperty(propertyName, out var node) && node.ValueKind == JsonValueKind.String
            ? node.GetString()
            : null;

    private static string? ParseContentPartsJson(JsonElement root)
    {
        if (!root.TryGetProperty("content_parts", out var node) || node.ValueKind != JsonValueKind.Array)
            return null;
        return node.GetRawText();
    }

    private static string? ParseJsonObjectProperty(JsonElement root, string propertyName)
    {
        if (!root.TryGetProperty(propertyName, out var node) || node.ValueKind != JsonValueKind.Object)
            return null;
        return node.GetRawText();
    }

    private static JsonNode? ParseJsonObjectNode(string? json)
    {
        if (string.IsNullOrWhiteSpace(json)) return null;
        try
        {
            return JsonNode.Parse(json) is JsonObject obj ? obj : null;
        }
        catch (JsonException)
        {
            return null;
        }
    }

    private static int ReadMetaInt(JsonElement root, string propertyName) =>
        root.TryGetProperty(propertyName, out var node)
        && node.ValueKind == JsonValueKind.Number
        && node.TryGetInt32(out var value)
            ? value
            : 0;

    /// <summary>
    /// Put the gauge back to where the last turn left it.
    ///
    /// Walks backwards to the newest turn that recorded a reading. A turn that also
    /// compacted is deliberately skipped rather than used: its reading describes the
    /// context <em>before</em> the cut, and restoring that would show a nearly full
    /// ring over a history that was just summarized down. The agent applies the same
    /// rule to its own reporting — there is no honest number again until the model
    /// replies once more.
    /// </summary>
    private void RestoreContextGauge(IReadOnlyList<PreparedMessage> messages)
    {
        var restore = SelectContextRestore(messages
            .Select(m => new ContextRestoreCandidate(
                m.Role == ChatMessage.RoleAssistant,
                m.ContextTokens,
                m.ContextWindow,
                m.CompactionTokensBefore))
            .ToList());

        if (restore.CompactedBefore > 0)
        {
            // Known to have compacted, size unknown. Surfacing that is the point:
            // it is why the ring is blank.
            ContextGauge.ContextWindow = restore.Window;
            ContextGauge.LastCompactionTokensBefore = restore.CompactedBefore;
        }
        else if (restore.Tokens > 0)
        {
            ContextGauge.Apply(new ContextUsageDelta(restore.Tokens, restore.Window));
        }
    }

    internal readonly record struct ContextRestoreCandidate(
        bool IsAssistant,
        int Tokens,
        int Window,
        int CompactedBefore);

    internal readonly record struct ContextRestore(int Tokens, int Window, int CompactedBefore);

    /// <summary>The decision half of <see cref="RestoreContextGauge"/>, separated so
    /// the compaction rule can be pinned without standing up a repository.</summary>
    internal static ContextRestore SelectContextRestore(IReadOnlyList<ContextRestoreCandidate> turns)
    {
        for (var i = turns.Count - 1; i >= 0; i--)
        {
            var turn = turns[i];
            if (!turn.IsAssistant) continue;
            if (turn.CompactedBefore > 0) return new ContextRestore(0, turn.Window, turn.CompactedBefore);
            if (turn.Tokens > 0 && turn.Window > 0) return new ContextRestore(turn.Tokens, turn.Window, 0);
        }
        return default;
    }

    private static Usage? ParseUsage(JsonElement root, string propertyName)
    {
        if (!root.TryGetProperty(propertyName, out var node) || node.ValueKind != JsonValueKind.Object)
            return null;

        var prompt = ReadInt(node, "promptTokens") ?? ReadInt(node, "prompt_tokens");
        var completion = ReadInt(node, "completionTokens") ?? ReadInt(node, "completion_tokens") ?? ReadInt(node, "answerTokens");
        var total = ReadInt(node, "totalTokens") ?? ReadInt(node, "total_tokens");
        return prompt is null && completion is null && total is null
            ? null
            : new Usage(prompt, completion, total);
    }

    private static (IReadOnlyList<MessageAttempt>? Attempts, int Current) ParseRetry(JsonElement root)
    {
        if (!root.TryGetProperty("retry", out var retry) || retry.ValueKind != JsonValueKind.Object)
            return (null, 0);
        if (!retry.TryGetProperty("attempts", out var attemptsNode) || attemptsNode.ValueKind != JsonValueKind.Array)
            return (null, 0);

        var attempts = new List<MessageAttempt>();
        foreach (var item in attemptsNode.EnumerateArray())
        {
            if (item.ValueKind == JsonValueKind.String)
            {
                var legacySplit = SplitInlineThinking(item.GetString());
                attempts.Add(new MessageAttempt(
                    legacySplit.Visible,
                    null,
                    null,
                    null,
                    Thinking: legacySplit.Thinking));
                continue;
            }
            if (item.ValueKind != JsonValueKind.Object) continue;
            var content = item.TryGetProperty("content", out var contentNode) && contentNode.ValueKind == JsonValueKind.String
                ? contentNode.GetString() ?? string.Empty
                : string.Empty;
            var modelLabel = item.TryGetProperty("model_label", out var modelNode) && modelNode.ValueKind == JsonValueKind.String
                ? modelNode.GetString()
                : null;
            var split = SplitInlineThinking(content);
            var thinking = ReadString(item, "thinking");
            if (!string.IsNullOrWhiteSpace(split.Thinking))
                thinking = string.IsNullOrWhiteSpace(thinking) ? split.Thinking : MergeThinking(thinking, split.Thinking);
            var toolCalls = ParseToolCalls(item);
            var thinkingSegments = ParseThinkingSegments(item);
            (toolCalls, thinkingSegments) = InferMissingTimelineIndexes(toolCalls, thinkingSegments);
            attempts.Add(new MessageAttempt(
                split.Visible,
                modelLabel,
                ParseUsage(item, "response_stats"),
                ParseSources(item),
                item.TryGetProperty("stopped", out var stoppedNode) && stoppedNode.ValueKind == JsonValueKind.True,
                thinking,
                thinkingSegments,
                toolCalls));
        }

        var current = ReadInt(retry, "current") ?? Math.Max(0, attempts.Count - 1);
        current = Math.Max(0, Math.Min(current, Math.Max(0, attempts.Count - 1)));
        return attempts.Count == 0 ? (null, 0) : (attempts, current);
    }

    private static IReadOnlyList<MessageAttempt>? RestoreCurrentRetryAttemptState(
        IReadOnlyList<MessageAttempt>? attempts,
        int current,
        string? thinking,
        IReadOnlyList<ThinkingSegmentDelta>? thinkingSegments,
        IReadOnlyList<ToolCallDelta>? toolCalls)
    {
        if (attempts is not { Count: > 0 } || current < 0 || current >= attempts.Count)
            return attempts;

        var restored = attempts.ToList();
        var attempt = restored[current];
        restored[current] = attempt with
        {
            Thinking = !string.IsNullOrWhiteSpace(thinking) ? thinking : attempt.Thinking,
            ThinkingSegments = thinkingSegments is { Count: > 0 } ? thinkingSegments : attempt.ThinkingSegments,
            ToolCalls = toolCalls is { Count: > 0 } ? toolCalls : attempt.ToolCalls
        };
        return restored;
    }

    private static IReadOnlyList<ToolCallDelta>? ParseToolCalls(JsonElement root)
    {
        if (!root.TryGetProperty("tool_calls", out var node) || node.ValueKind != JsonValueKind.Array)
            return null;

        var list = new List<ToolCallDelta>();
        var fallbackIndex = 1;
        foreach (var item in node.EnumerateArray())
        {
            if (item.ValueKind != JsonValueKind.Object) continue;
            var name = ReadString(item, "name");
            var label = ReadString(item, "label");
            if (string.IsNullOrWhiteSpace(name) && string.IsNullOrWhiteSpace(label)) continue;
            name = RestoreToolName(name, label);
            var id = ReadString(item, "id");
            if (string.IsNullOrWhiteSpace(id))
                id = $"restored-tool-{fallbackIndex}";

            list.Add(new ToolCallDelta(
                id!,
                name,
                ReadString(item, "status") ?? "completed",
                label,
                ReadString(item, "summary"),
                ReadString(item, "detail"),
                ReadString(item, "arguments_json") ?? ReadString(item, "argumentsJson"),
                ReadString(item, "result_preview_json") ?? ReadString(item, "resultPreviewJson"),
                ReadString(item, "provider"),
                ReadInt(item, "content_offset") ?? ReadInt(item, "contentOffset"),
                ReadInt(item, "timeline_index") ?? ReadInt(item, "timelineIndex")));
            fallbackIndex++;
        }

        return list.Count == 0 ? null : list;
    }

    private static string RestoreToolName(string? name, string? label)
    {
        if (!string.IsNullOrWhiteSpace(name)) return name;
        return label switch
        {
            "联网搜索" => "search_web",
            "网页阅读" => "web_fetch",
            "Python" => "execute_python_code",
            "读取文件" => "read_file",
            "查找文件" => "glob_files",
            "搜索内容" => "grep_files",
            "查看图片" => "view_image",
            "图片分析" => "analyze_image",
            "生成图片" => "generate_image",
            _ => string.Empty
        };
    }

    private static IReadOnlyList<ThinkingSegmentDelta>? ParseThinkingSegments(JsonElement root)
    {
        if (!root.TryGetProperty("thinking_segments", out var node) || node.ValueKind != JsonValueKind.Array)
            return null;

        var list = new List<ThinkingSegmentDelta>();
        foreach (var item in node.EnumerateArray())
        {
            if (item.ValueKind != JsonValueKind.Object) continue;
            var source = ReadString(item, "source");
            if (string.IsNullOrWhiteSpace(source)) continue;
            list.Add(new ThinkingSegmentDelta(
                source!,
                ReadInt(item, "content_offset") ?? ReadInt(item, "contentOffset") ?? 0,
                ReadDouble(item, "elapsed_seconds") ?? ReadDouble(item, "elapsedSeconds") ?? 0,
                ReadInt(item, "timeline_index") ?? ReadInt(item, "timelineIndex")));
        }

        return list.Count == 0 ? null : list;
    }

    private static (IReadOnlyList<ToolCallDelta>? ToolCalls, IReadOnlyList<ThinkingSegmentDelta>? ThinkingSegments)
        InferMissingTimelineIndexes(IReadOnlyList<ToolCallDelta>? toolCalls, IReadOnlyList<ThinkingSegmentDelta>? thinkingSegments)
    {
        if ((toolCalls is null || toolCalls.Count == 0) && (thinkingSegments is null || thinkingSegments.Count == 0))
            return (toolCalls, thinkingSegments);

        var hasPersistedTimeline =
            toolCalls?.Any(t => t.TimelineIndex is not null) == true
            || thinkingSegments?.Any(t => t.TimelineIndex is not null) == true;

        // Phase 1 — legacy data with no timeline at all: derive a display order
        // from content offsets so tools/thinking interleave as they streamed.
        if (!hasPersistedTimeline)
            (toolCalls, thinkingSegments) = InferTimelineFromOffsets(toolCalls, thinkingSegments);

        // Phase 2 — backfill any tool that is missing its content offset. On
        // restore the VM already holds the full message text, so a null offset
        // would make ApplyToolDelta pin the card to Content.Length (the very
        // end). Inheriting the preceding element's offset (timeline order)
        // keeps the card at its original spot — including inside the thinking
        // area, preserving the streamed layout.
        if (toolCalls?.Any(t => t.ContentOffset is null) == true)
            toolCalls = BackfillMissingToolOffsets(toolCalls, thinkingSegments);

        return (toolCalls, thinkingSegments);
    }

    private static (IReadOnlyList<ToolCallDelta>? ToolCalls, IReadOnlyList<ThinkingSegmentDelta>? ThinkingSegments)
        InferTimelineFromOffsets(IReadOnlyList<ToolCallDelta>? toolCalls, IReadOnlyList<ThinkingSegmentDelta>? thinkingSegments)
    {
        var toolIndexes = new Dictionary<int, int>();
        var thinkingIndexes = new Dictionary<int, int>();
        var toolGroups = (toolCalls ?? [])
            .Select((item, index) => new IndexedTool(item, index))
            .GroupBy(t => t.Item.ContentOffset ?? 0)
            .ToDictionary(g => g.Key, g => g.ToList());
        var thinkingGroups = (thinkingSegments ?? [])
            .Select((item, index) => new IndexedThinking(item, index))
            .GroupBy(t => t.Item.ContentOffset)
            .ToDictionary(g => g.Key, g => g.ToList());

        var sequence = 0;
        foreach (var offset in toolGroups.Keys.Concat(thinkingGroups.Keys).Distinct().OrderBy(x => x))
        {
            toolGroups.TryGetValue(offset, out var toolsAtOffset);
            thinkingGroups.TryGetValue(offset, out var thinkingAtOffset);
            var count = Math.Max(toolsAtOffset?.Count ?? 0, thinkingAtOffset?.Count ?? 0);
            for (var i = 0; i < count; i++)
            {
                if (thinkingAtOffset is not null && i < thinkingAtOffset.Count)
                    thinkingIndexes[thinkingAtOffset[i].Index] = sequence++;
                if (toolsAtOffset is not null && i < toolsAtOffset.Count)
                    toolIndexes[toolsAtOffset[i].Index] = sequence++;
            }
        }

        var restoredTools = toolCalls?.Select((t, i) => t with { TimelineIndex = toolIndexes[i] }).ToList();
        var restoredThinking = thinkingSegments?.Select((t, i) => t with { TimelineIndex = thinkingIndexes[i] }).ToList();
        return (restoredTools, restoredThinking);
    }

    private static IReadOnlyList<ToolCallDelta> BackfillMissingToolOffsets(
        IReadOnlyList<ToolCallDelta> toolCalls,
        IReadOnlyList<ThinkingSegmentDelta>? thinkingSegments)
    {
        // Walk all elements in timeline order, carrying the last known content
        // offset forward. Thinking offsets are always concrete; only tools can
        // be null. A null-offset tool before any known offset lands at 0.
        var events = new List<(int? Timeline, int Order, int ToolIndex, int? Offset)>();
        for (var i = 0; i < toolCalls.Count; i++)
            events.Add((toolCalls[i].TimelineIndex, i, i, toolCalls[i].ContentOffset));
        if (thinkingSegments is not null)
            for (var i = 0; i < thinkingSegments.Count; i++)
                events.Add((thinkingSegments[i].TimelineIndex, toolCalls.Count + i, -1, thinkingSegments[i].ContentOffset));

        var resolved = new int[toolCalls.Count];
        for (var i = 0; i < toolCalls.Count; i++)
            resolved[i] = toolCalls[i].ContentOffset ?? 0;

        var lastOffset = 0;
        foreach (var e in events.OrderBy(e => e.Timeline ?? int.MaxValue).ThenBy(e => e.Order))
        {
            if (e.Offset is { } known)
                lastOffset = known;
            else if (e.ToolIndex >= 0)
                resolved[e.ToolIndex] = lastOffset;
        }

        return toolCalls
            .Select((t, i) => t.ContentOffset is null ? t with { ContentOffset = resolved[i] } : t)
            .ToList();
    }

    private sealed record IndexedTool(ToolCallDelta Item, int Index);
    private sealed record IndexedThinking(ThinkingSegmentDelta Item, int Index);

    private static int? ReadInt(JsonElement obj, string name)
    {
        if (!obj.TryGetProperty(name, out var value)) return null;
        if (value.ValueKind == JsonValueKind.Number && value.TryGetInt32(out var number)) return number;
        if (value.ValueKind == JsonValueKind.String && int.TryParse(value.GetString(), out var parsed)) return parsed;
        return null;
    }

    private static double? ReadDouble(JsonElement obj, string name)
    {
        if (!obj.TryGetProperty(name, out var value)) return null;
        if (value.ValueKind == JsonValueKind.Number && value.TryGetDouble(out var number)) return number;
        if (value.ValueKind == JsonValueKind.String && double.TryParse(value.GetString(), out var parsed)) return parsed;
        return null;
    }

    private static string? ReadString(JsonElement obj, string name)
    {
        if (!obj.TryGetProperty(name, out var value)) return null;
        return value.ValueKind == JsonValueKind.String ? value.GetString() : null;
    }

    public static string GenerateTitle(string? content)
    {
        content = (content ?? string.Empty)
            .Replace("\r", " ")
            .Replace("\n", " ")
            .Trim();
        content = MessageViewModel.StripSystemHints(content);

        var title = content.Length <= 25 ? content : content[..25].Trim() + "...";
        return string.IsNullOrWhiteSpace(title) ? "无标题对话" : title;
    }

    public static InlineThinkingParts SplitInlineThinking(string? content)
    {
        if (string.IsNullOrEmpty(content))
            return new InlineThinkingParts(string.Empty, null);

        if (IndexOfIgnoreCase(content, "<think") >= 0)
            return SplitInlineThinkTags(content);

        var splitter = new InlineThinkSplitter();
        var fed = splitter.Feed(content);
        var flushed = splitter.Flush();
        var visible = fed.Visible + flushed.Visible;
        var thinking = fed.Thinking + flushed.Thinking;

        return new InlineThinkingParts(visible, string.IsNullOrWhiteSpace(thinking) ? null : thinking.Trim());
    }

    private static InlineThinkingParts SplitInlineThinkTags(string content)
    {
        var visible = new StringBuilder();
        var thinking = new StringBuilder();
        var pos = 0;

        while (pos < content.Length)
        {
            var nextThink = IndexOfIgnoreCase(content, "<think", pos);
            if (nextThink < 0)
            {
                visible.Append(content, pos, content.Length - pos);
                break;
            }

            if (nextThink > pos)
                visible.Append(content, pos, nextThink - pos);

            var openEnd = content.IndexOf('>', nextThink);
            if (openEnd < 0)
            {
                AppendThinkingSegment(thinking, content[nextThink..]);
                break;
            }

            var bodyStart = openEnd + 1;
            var close = IndexOfIgnoreCase(content, "</think>", bodyStart);
            if (close < 0)
            {
                AppendThinkingSegment(thinking, content[bodyStart..]);
                break;
            }

            AppendThinkingSegment(thinking, content[bodyStart..close]);
            pos = close + "</think>".Length;
        }

        var thinkingText = thinking.ToString().Trim();
        return new InlineThinkingParts(
            visible.ToString().TrimStart(),
            string.IsNullOrWhiteSpace(thinkingText) ? null : thinkingText);
    }

    private static void AppendThinkingSegment(StringBuilder builder, string? segment)
    {
        if (string.IsNullOrWhiteSpace(segment)) return;
        var text = segment.Trim();
        if (builder.Length > 0 && !EndsWithBlankLine(builder))
            builder.Append("\n\n");
        builder.Append(text);
    }

    private static bool EndsWithBlankLine(StringBuilder builder)
    {
        if (builder.Length < 2) return false;
        var last = builder[builder.Length - 1];
        var prev = builder[builder.Length - 2];
        return (last == '\n' && prev == '\n') || (last == '\n' && prev == '\r');
    }

    private static int IndexOfIgnoreCase(string source, string value, int start = 0)
    {
        return source.IndexOf(value, start, StringComparison.OrdinalIgnoreCase);
    }

    private static string MergeThinking(string first, string? second)
    {
        if (string.IsNullOrWhiteSpace(second)) return first;
        if (first.Contains(second, StringComparison.Ordinal)) return first;
        if (second.Contains(first, StringComparison.Ordinal)) return second;
        return first.TrimEnd() + "\n\n" + second.TrimStart();
    }

    private static bool IsRoutesModel(ProviderModel? model)
    {
        if (model is null) return false;
        return string.Equals(model.Id, "autoLLM", StringComparison.OrdinalIgnoreCase)
            || model.DisplayName.Contains("MolaGPT Routes", StringComparison.OrdinalIgnoreCase);
    }

    partial void OnActiveProviderChanged(IChatProvider? value)
    {
        OnPropertyChanged(nameof(ActiveProviderLabel));
    }

    partial void OnActiveModelChanged(ProviderModel? value)
    {
        OnPropertyChanged(nameof(ActiveModelLabel));
    }

    partial void OnAutoCollapseThinkingChanged(bool value)
    {
        foreach (var message in Messages)
            message.AutoCollapseThinkingOnComplete = value;
    }

}

public sealed record InlineThinkingParts(string Visible, string? Thinking);

public sealed class ConversationTouchedEventArgs : EventArgs
{
    public ConversationTouchedEventArgs(string id, string title, DateTimeOffset updatedAt, string? providerId)
        : this(id, title, updatedAt, providerId, null) { }

    public ConversationTouchedEventArgs(string id, string title, DateTimeOffset updatedAt, string? providerId, string? personaLabel)
    {
        Id = id;
        Title = title;
        UpdatedAt = updatedAt;
        ProviderId = providerId;
        PersonaLabel = personaLabel;
    }
    public string Id { get; }
    public string Title { get; }
    public DateTimeOffset UpdatedAt { get; }
    public string? ProviderId { get; }
    /// <summary>Persona display name bound to this conversation, or null when
    /// no persona is attached. Surfaced in the sidebar as the badge label.</summary>
    public string? PersonaLabel { get; }
}
